### ISSUE TITLE
when running evaluate with DDPG always choose sell

### ISSUE THREAD

**Issue by yesungkeke** [Albert-Z-Guo/Deep-Reinforcement-Stock-Trading#10]
when I was running "evaluate.py" with DDPG ,agent always choose "sell"(action = 2).Could you tell me how to solve?

**Comment by Albert-Z-Guo** [comment]
Hi, thanks for reaching out! 

Poor evaluation behavior is likely due to poor learning from training the agent due to various reasons. This project was a toy project when I was learning deep reinforcement learning myself. For better framework and closer to real world trading applications, I'd recommend trying this repository: https://github.com/AI4Finance-Foundation/FinRL

Keep learning!
